spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/java_auth_api_sample_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  web:
    cors:
      allowed-origins: 'http://localhost:8080'
      allowed-methods: 'GET,POST,PUT,DELETE,OPTIONS'
      allowed-headers: '*'
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: HikariCP
  data:
    redis:
      host: localhost
      port: 6379

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.example.api.auth.model
  type-handlers-package: com.example.api.common.mybatis
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30

server:
  port: 8080

# JWT Configuration
jwt:
  secret: ${JWT_SECRET}
  algorithm: HS512
  access-token-expiration: ${ACCESS_TOKEN_EXPIRATION}
  refresh-token-expiration: ${REFRESH_TOKEN_EXPIRATION}

# OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    enabled: true

logging:
  level:
    org.springframework.web: DEBUG
    org.springdoc: DEBUG

springsecurity:
  basic:
    enabled: false
  web:
    ignore:
      - /swagger-ui.html
      - /v3/api-docs
      - /swagger-ui/**
      - /v3/api-docs/**
