spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_api
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  web:
    cors:
      allowed-origins: 'http://localhost:8080'
      allowed-methods: 'GET,POST,PUT,DELETE,OPTIONS'
      allowed-headers: '*'

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.authapi.model
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30

server:
  port: 8080

# JWT Configuration
jwt:
  secret: yourSecretKey12345678901234567890123456789012
  access-token-expiration: 300000 # 5 minutes in milliseconds
  refresh-token-expiration: 604800000 # 7 days in milliseconds

# OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    enabled: true

logging:
  level:
    org.springframework.web: DEBUG
    org.springdoc: DEBUG

springsecurity:
  basic:
    enabled: false
  web:
    ignore:
      - /swagger-ui.html
      - /v3/api-docs
      - /swagger-ui/**
      - /v3/api-docs/**
