name: java-auth-api-sample
services:
  postgres:
    image: postgres:16
    container_name: java-auth-postgres
    environment:
      POSTGRES_DB: java_auth_api_sample_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./docker/data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: java-auth-redis
    ports:
      - '6379:6379'
    volumes:
      - ./docker/redis:/data
    command: redis-server --save 60 1 --loglevel warning
