name: java-auth-api-sample
services:
  postgres:
    image: postgres:16
    container_name: java-auth-postgres
    environment:
      POSTGRES_DB: auth_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./docker/data:/var/lib/postgresql/data
